### ISSUE TITLE
add docs directory to cookiecutter template with the necessary tooling to build

### ISSUE THREAD

**Issue by lila** [GoogleCloudPlatform/solutions-template#30]
it would be nice to have the cookiecutter template that is created to include a docs directory that has the docs-as-code templates.  for example https://github.com/lila/readthedoc-test  uses sphinx and github actions to build and deploy in github pages.  other frameworks are fine too...

**Comment by jonchenn** [comment]
Thanks for the good suggestion, Karan. We use FastAPI that automatically generates swagger API docs, and we also use Redoc (https://github.com/Redocly/redoc) for the doc UI. I'll add these to this template documentation.

**Comment by lavjain** [comment]
Cookiecutter has been replaced by copier
