### ISSUE TITLE
Letencrypt cert is not valid in the ingress

### ISSUE THREAD

**Issue by jonchenn** [GoogleCloudPlatform/solutions-template#35]
The ingress is currently using "letsencrypt" cert issuer: https://github.com/GoogleCloudPlatform/solutions-template/blob/main/terraform/modules/ingress/main.tf#L37

However the cert is not valid out of the box. Need to look into the TF module that generates the cert.

**Comment by lila** [comment]
@jonchenn see https://github.com/gavinbunney/terraform-provider-kubectl/issues/177 

the fix seems to be to add the line:
`load_config_file = false`

to ./terraform/environment/dev/provider.tf in the section for kubectl:
```
# Used by module.ingress.
provider "kubectl" {
  load_config_file       = false
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
}
```

i can confirm that adding the line resolves the issue where terrform --apply produces the following error:

```
module.ingress.module.cert_manager.kubectl_manifest.cluster_issuer[0]: Creating...
╷
│ Error: letsencrypt failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
│ 
│   with module.ingress.module.cert_manager.kubectl_manifest.cluster_issuer[0],
│   on .terraform/modules/ingress.cert_manager/main.tf line 42, in resource "kubectl_manifest" "cluster_issuer":
│   42: resource "kubectl_manifest" "cluster_issuer" {
│ 
╵
```

**Comment by jonchenn** [comment]
@lavjain Have you found any resolution for this?

**Comment by jwh-hutchison** [comment]
@lavjain I am also having this issue, have you found any fix for this?

**Comment by jonchenn** [comment]
Hi @jwh-hutchison thanks for pinging here, @lavjain is working on fixing this, ETA would be by next week.

**Comment by jonchenn** [comment]
Hi @jwh-hutchison , sorry for a bit delay. We had a major refactor on the Terraform structure at https://github.com/GoogleCloudPlatform/solutions-template/pull/34, and many other fixes after that.

We've tested a while and we no longer see the letsecrypt errors in the Terraform apply steps. However, please note that in order to use TLS/SSL with letsencrypts, you would need extra steps. We will add more steps and documentation around this later.

Closing this issue as the error is resolved now. Thanks!
