### ISSUE TITLE
error when deploying optional cloudrun application

### ISSUE THREAD

**Issue by lila** [GoogleCloudPlatform/solutions-template#37]
when i uncomment the optional cloudrun service in main.tf (./terraform/environments/dev/main.tf), and run terraform apply,  i get the following error:

```
module.cloudrun-sample.null_resource.deploy-cloudrun-image: Creation complete after 2m34s [id=6824479577047599322]
╷
│ Error: Error applying IAM policy for cloudrun service "v1/projects/solution1-373714/locations/us-central1/services/cloudrun-sample": Error setting IAM policy for cloudrun service "v1/projects/solution1-373714/locations/us-central1/services/cloudrun-sample": googleapi: Error 404: Resource 'cloudrun-sample' of kind 'SERVICE' in region 'us-central1' in project 'solution1-373714' does not exist.
│ 
│   with module.cloudrun-sample.google_cloud_run_service_iam_member.member[0],
│   on ../../modules/cloudrun/main.tf line 12, in resource "google_cloud_run_service_iam_member" "member":
│   12: resource "google_cloud_run_service_iam_member" "member" {
│ 
╵
```

note that the service does deploy and is functional, but the error still exists... not sure why.

thanks

k

**Comment by lila** [comment]
maybe a timing issue... when i reran it, it worked ...

- k

**Comment by jonchenn** [comment]
Thanks for reporting this. Let me retry the scenario and will add these caveat to the documentation.

**Comment by jonchenn** [comment]
Added documentation here: https://github.com/GoogleCloudPlatform/solutions-template/pull/34

**Comment by jonchenn** [comment]
This is fixed by refactoring TF structure to stages. https://github.com/GoogleCloudPlatform/solutions-template/pull/34
