### ISSUE TITLE
[FR] Use GKE native ingress instead of Nginx ingress

### ISSUE THREAD

**Issue by jonchenn** [GoogleCloudPlatform/solutions-template#9]
- Currently the template uses Nginx ingress
- Recommended to migrate to use Container-native load balancing: 
    - https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer

**Comment by lavjain** [comment]
Fixed by https://github.com/GoogleCloudPlatform/solutions-template/pull/69
